---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: asotobue-dev
  labels:
    app.kubernetes.io/name: hello-world
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-world
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-world
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: quay.io/lordofthejars/hello-world:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          name: hello-world
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  namespace: asotobue-dev
  annotations:
    app.quarkus.io/commit-id: 277270f3f2a7b0e78c69b3be83be372c7e6ca693
    app.quarkus.io/build-timestamp: 2023-03-08 - 08:51:15 +0000
  labels:
    app.kubernetes.io/name: hello-world
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: hello-world
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: hello-world
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
