---
- name: Capture POSTs from gitea
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
      filters:
        - ansible.eda.dashes_to_underscores:

  rules:
    - name: Print Important Data
      condition: event.meta.headers.X_GitHub_Event == "push"
      action:
        echo:
          message: "A change in {{ event.meta.headers.X_GitHub_Event }} in repo {{event.payload.repository.name}} URL {{event.payload.repository.clone_url}}."

